// <auto-generated />
using System;
using FourPointImport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FourPointImport.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230614210350_SecondImport")]
    partial class SecondImport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FourPointImport.Data.Import", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("FourPointImport.Data.billingDetail", b =>
                {
                    b.HasBaseType("FourPointImport.Data.Import");

                    b.Property<int>("BDSEQ")
                        .HasColumnType("int");

                    b.Property<string>("BXAGNT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("BXBAMT")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BXBGRS")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BXBRCH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("BXCAND")
                        .HasColumnType("datetime2");

                    b.Property<string>("BXCERT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BXCODE")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("BXCOMM")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BXCOMP")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BXCOVC")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BXDESC")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("BXEFFT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BXEXPR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BXFROM")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BXINT")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("BXINTR")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("BXMOB")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BXMSGC")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BXMSGD")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("BXNAME")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("BXNEG01")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BXNEG02")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BXNEG03")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BXNEG04")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BXNEG05")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BXNEG06")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BXNEG07")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("BXNEXT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BXPAID")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BXPAMT")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BXPGRS")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BXPRIN")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<decimal>("BXSCHD")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<DateTime>("BXTHRU")
                        .HasColumnType("datetime2");

                    b.ToTable("BillingDetail", "dbo");
                });

            modelBuilder.Entity("FourPointImport.Data.FormMaster", b =>
                {
                    b.HasBaseType("FourPointImport.Data.Import");

                    b.Property<string>("FmAGNT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FmCalc")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("FmDATA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FmDATC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FmDATU")
                        .HasColumnType("datetime2");

                    b.Property<string>("FmDesc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("FmEfft")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FmExpr")
                        .HasColumnType("datetime2");

                    b.Property<int>("FmForm")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("FmLend")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FmType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FmUSRA")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FmUSRC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FmUSRU")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.ToTable("FormMaster", "dbo");
                });

            modelBuilder.Entity("FourPointImport.Data.SuspenseMaster", b =>
                {
                    b.HasBaseType("FourPointImport.Data.Import");

                    b.Property<string>("SmAdd11")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmAdd12")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmAdd21")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmAdd22")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmAgnt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SmAmnt")
                        .HasPrecision(11, 2)
                        .HasColumnType("int");

                    b.Property<string>("SmBall")
                        .IsRequired()
                        .HasPrecision(11, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmBen1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SmBen2")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmBrch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmCalc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SmCert")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SmCert2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SmCity1")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmCity2")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("SmCnl")
                        .HasColumnType("int");

                    b.Property<int>("SmCnlD")
                        .HasColumnType("int");

                    b.Property<int>("SmCnlL")
                        .HasColumnType("int");

                    b.Property<decimal>("SmComR")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("SmDAmt")
                        .HasPrecision(11, 7)
                        .HasColumnType("decimal(11,7)");

                    b.Property<int>("SmDBen")
                        .HasPrecision(11, 2)
                        .HasColumnType("int");

                    b.Property<string>("SmDChg")
                        .IsRequired()
                        .HasPrecision(11, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SmDatU")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmData")
                        .HasColumnType("datetime2");

                    b.Property<int>("SmDays")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<string>("SmDeal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SmDebt")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal>("SmDis")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<DateTime>("SmDob1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmDob2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmEffD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmEffL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmEffP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmEfft")
                        .HasColumnType("datetime2");

                    b.Property<int>("SmExcP")
                        .HasColumnType("int");

                    b.Property<string>("SmExcd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("SmExpD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmExpL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmExpP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmExpr")
                        .HasColumnType("datetime2");

                    b.Property<string>("SmFNam1")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmFNam2")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("SmFPay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SmFPrm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SmFee")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<string>("SmFlag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("SmForm")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("SmFreq")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<int>("SmFut1")
                        .HasPrecision(5)
                        .HasColumnType("int");

                    b.Property<int>("SmFut2")
                        .HasPrecision(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("SmGDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SmGEfft")
                        .HasColumnType("int");

                    b.Property<int>("SmGExpr")
                        .HasColumnType("int");

                    b.Property<string>("SmGStat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SmHQ01A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ01B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ02A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ02B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ03A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ03B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ04A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ04B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ05A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ05B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ06A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ06B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ07A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ07B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ08A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ08B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ09A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ09B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ10A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ10B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ11A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ11B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ12A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ12B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ13A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ13B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ14A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ14B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ15A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ15B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ16A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ16B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ17A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ17B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ18A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ18B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ19A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ19B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ20A")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmHQ20B")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("SmIdn1")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<int>("SmIdn2")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<decimal>("SmIntr")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("SmLAmt")
                        .HasPrecision(11, 7)
                        .HasColumnType("decimal(11,7)");

                    b.Property<int>("SmLBen")
                        .HasPrecision(11, 2)
                        .HasColumnType("int");

                    b.Property<string>("SmLChg")
                        .IsRequired()
                        .HasPrecision(11, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmLNam1")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmLNam2")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmLend")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("SmLif")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal>("SmLine")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<string>("SmMNam1")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmMNam2")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SmMake")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SmModel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SmOffc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SmPanI")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.Property<decimal>("SmPhne1")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.Property<decimal>("SmPhne2")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("SmRegn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmSchd")
                        .HasPrecision(11, 2)
                        .HasColumnType("int");

                    b.Property<string>("SmSex1")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmSex2")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmSig1")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SmSig2")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("SmSovD")
                        .HasColumnType("int");

                    b.Property<string>("SmSovS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SmSte1")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SmSte2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SmSufx1")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SmSufx2")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("SmTerm")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<string>("SmTerr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmTrmD")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<int>("SmTrmL")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<int>("SmTrmP")
                        .HasPrecision(3)
                        .HasColumnType("int");

                    b.Property<string>("SmType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SmUsrA")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SmUsrU")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SmVIN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SmYear")
                        .HasColumnType("int");

                    b.Property<string>("SmZip1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SmZip2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Smmntf")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.ToTable("SuspenseMaster", "dbo");
                });

            modelBuilder.Entity("FourPointImport.Data.billingDetail", b =>
                {
                    b.HasOne("FourPointImport.Data.Import", null)
                        .WithOne()
                        .HasForeignKey("FourPointImport.Data.billingDetail", "id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FourPointImport.Data.FormMaster", b =>
                {
                    b.HasOne("FourPointImport.Data.Import", null)
                        .WithOne()
                        .HasForeignKey("FourPointImport.Data.FormMaster", "id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FourPointImport.Data.SuspenseMaster", b =>
                {
                    b.HasOne("FourPointImport.Data.Import", null)
                        .WithOne()
                        .HasForeignKey("FourPointImport.Data.SuspenseMaster", "id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
