namespace FourPointImport.Web.Models
{
    public class billingExport
    {
        public string PgmNam { get; set; }
        public string NParms { get; set; }
        public string LibNam { get; set; }
        public string WsId { get; set; }
        public string UserId { get; set; }
        public string JobNbr { get; set; }
        public DateTime JobDte { get; set; }
        public DateTime SyDte { get; set; }
        public string JobTme { get; set; }
        public DateTime CmpDte { get; set; }
        public string CmpTme { get; set; }
        public string CmpLvl { get; set; }
        public string SrcFil { get; set; }
        public string SrcLib { get; set; }
        public string SrcMbr { get; set; }
        public string SeAgnt { get; set; }
        public string SeDebtCode { get; set; }
        public string SusMstl3 { get; set; }
        public DateTime SeEfft { get; set; }
        public DateTime SeEffL { get; set; }
        public DateTime SeEffl { get; set; }
        public DateTime SeEffD { get; set; }
        public DateTime SeEffP { get; set; }
        public decimal SeLif { get; set; }
        public int SeTrmL { get; set; }
        public int SeTerm { get; set; }
        public string? SeType { get; set; }
        public string SeDis { get; set; }
        public DateTime SysDte { get; set; }
        public int SeTrmD { get; set; }
        public DateTime SeExpP { get; set; }
        public DateTime SeExpr { get; set; }
        public int SeTrmP { get; set; }
        public int SeFut17 { get; set; }
        public int SeForm { get; set; }
        public int FrmMstL1 { get; set; }
        public string SeCalc { get; set; }
        public int F1Calc { get; set; }
        public int Key_Calc { get; set; }
        public string SeLend { get; set; }
        public string FrmMstL2 { get; set; }
        public DateTime F2Efft { get; set; }
        public DateTime F2Expr { get; set; }
        public int F2Form { get; set; }
        public decimal Key02_Fld01 { get; set; }
        public string Key02_Fld02 { get; set; }
        public string S07R { get; set; }
        public string Key03_Fld01 { get; set; }
        public string Key03_Fld02 { get; set; }
        public DateTime WorkDate3 { get; set; }
        public DateTime SeFPay { get; set; }
        public int SeFreq { get; set; }
        public DateTime SeFPrm { get; set; }
        public int seTerm { get; set; }
        public int SeEffp { get; set; }
        public decimal SeDebt { get; set; }
        public string LType { get; set; }
        public string LType_Char1 { get; set; }
        public string Ltype { get; set; }
        public decimal SeFut1 { get; set; }
        public decimal SeFut2 { get; set; }
        public string Key04_Fld01 { get; set; }
        public string SelNam1 { get; set; }
        public string SefNam1 { get; set; }
        public int SeIDN1 { get; set; }
        public int SeIDN2 { get; set; }
        public string CmIDN1 { get; set; }
        public string SeTerr { get; set; }
        public string SeBrch { get; set; }
        public string SeOffc { get; set; }
        public string SeCert { get; set; }
        public string SeBen1 { get; set; }
        public string SeBen2 { get; set; }
        public int SeDays { get; set; }
        public DateTime SeFpay { get; set; }
        public int SeAmnt { get; set; }
        public string SeBall { get; set; }
        public decimal SeIntr { get; set; }
        public decimal SeSchd { get; set; }
        public decimal SeLAmt { get; set; }
        public decimal SeDAmt { get; set; }
        public string SeLChg { get; set; }
        public string SeDChg { get; set; }
        public DateTime seExpr { get; set; }
        public string SeRegn { get; set; }
        public int SeLBen { get; set; }
        public int SeDBen { get; set; }
        public int SmCalc { get; set; }
        public DateTime SeExpL { get; set; }
        public int SeTrm { get; set; }
        public DateTime SeExpD { get; set; }
        public int SeIdn1 { get; set; }
        public string SeLNam1 { get; set; }
        public string SeMNam1 { get; set; }
        public string SeSufx1 { get; set; }
        public string SeAdd11 { get; set; }
        public string SeAdd21 { get; set; }
        public string SeCity1 { get; set; }
        public string SeSte1 { get; set; }
        public string SeZip1 { get; set; }
        public string SeFNam1 { get; set; }
        public decimal SePhne1 { get; set; }
        public DateTime SeDob1 { get; set; }
        public string SeSex1 { get; set; }
        public string SeHQ01A { get; set; }
        public string SeHQ02A { get; set; }
        public string SeHQ03A { get; set; }
        public string SeHQ04A { get; set; }
        public string SeHQ05A { get; set; }
        public string SeHQ06A { get; set; }
        public string SeHQ07A { get; set; }
        public string SeHQ08A { get; set; }
        public string SeHQ09A { get; set; }
        public string SeHQ10A { get; set; }
        public string SeHQ11A { get; set; }
        public string SeHQ12A { get; set; }
        public string SeHQ13A { get; set; }
        public string SeHQ14A { get; set; }
        public string SeHQ15A { get; set; }
        public string SeHQ16A { get; set; }
        public string SeHQ17A { get; set; }
        public string SeHQ18A { get; set; }
        public string SeHQ19A { get; set; }
        public string SeHQ20A { get; set; }
        public string SeSig1 { get; set; }
        public int SeIdn2 { get; set; }
        public string SeLNam2 { get; set; }
        public string SeFNam2 { get; set; }
        public string SeMNam2 { get; set; }
        public string SeSufx2 { get; set; }
        public string SeAdd12 { get; set; }
        public string SeAdd22 { get; set; }
        public string SeCity2 { get; set; }
        public string SeSte2 { get; set; }
        public string SeZip2 { get; set; }
        public decimal SePhne2 { get; set; }
        public DateTime SeDob2 { get; set; }
        public string SeSex2 { get; set; }
        public string SeHQ01B { get; set; }
        public string SeHQ02B { get; set; }
        public string SeHQ03B { get; set; }
        public string SeHQ04B { get; set; }
        public string SeHQ05B { get; set; }
        public string SeHQ06B { get; set; }
        public string SeHQ07B { get; set; }
        public string SeHQ08B { get; set; }
        public string SeHQ09B { get; set; }
        public string SeHQ10B { get; set; }
        public string SeHQ11B { get; set; }
        public string SeHQ12B { get; set; }
        public string SeHQ13B { get; set; }
        public string SeHQ14B { get; set; }
        public string SeHQ15B { get; set; }
        public string SeHQ16B { get; set; }
        public string SeHQ17B { get; set; }
        public string SeHQ18B { get; set; }
        public string SeHQ19B { get; set; }
        public string SeHQ20B { get; set; }
        public string SeSig2 { get; set; }
        public string SeFlag { get; set; }                  //new or update N/U
        public decimal SeCnl { get; set; }
        public int SeCnlL { get; set; }
        public int SeCnlD { get; set; }
        public string SeSovS { get; set; }
        public int SeSovD { get; set; }
        public decimal SePanI { get; set; }                     //this is a combination of BFINT and BRPFIN
        public decimal SeLine { get; set; }
        public string SeDeal { get; set; }
        public decimal SeMntf { get; set; }
        public string SeCert2 { get; set; }
        public string SeVIN { get; set; }
        public int SeYear { get; set; }
        public string SeMake { get; set; }
        public string SeModel { get; set; }
        public decimal SeFee { get; set; }
        public decimal SeComR { get; set; }
        public int SeGEfft { get; set; }
        public int SeGExpr { get; set; }
        public string SeGStat { get; set; }
        public DateTime SeGDate { get; set; }
        public string BFFROM { get; set; }
        public DateTime BFTHRU { get; set; }
        public string BFPAID { get; set; }
        public string BFNEXT { get; set; }
        public string BFCOMM { get; set; }
        public decimal BFBGRS { get; set; }
        public string BFGRS { get; set; }
        public string BFMOB { get; set; }
        public decimal BFInt { get; set; }
        public string BFPRIN { get; set; }
        public string BFMSGC { get; set; }
        public string BFMSGD { get; set; }
        public string BFDESC { get; set; }
        public string BFCAND { get; set; }
    }
}
